PROBLEMS = [
    {
        "id": "two-sum",
        "title": "Two Sum",
        "prompt": "Given an array of integers nums and an integer target, return the indices of the two numbers such that they add up to target. You may assume that each input has exactly one solution.",
        "pattern": "Hash Map",
        "choices": ["Sliding Window", "Hash Map", "Binary Search", "Dynamic Programming"],
        "explanation": "A hash map allows you to store previously seen numbers and check in constant time whether the complement exists.",
        "clues": [
            "Need fast lookup of previously seen values",
            "Searching for complements",
            "Optimal solution is O(n)",
        ],
        "complexity": "O(n)",
    },
    {
        "id": "best-time-stock",
        "title": "Best Time to Buy and Sell Stock",
        "prompt": "You are given an array prices where prices[i] is the price of a stock on day i. Find the maximum profit you can achieve by buying once and selling once.",
        "pattern": "Sliding Window",
        "choices": ["Depth First Search", "Sliding Window", "Heap", "Graph Traversal"],
        "explanation": "Track the minimum price seen so far while scanning through the array and compute profit windows dynamically.",
        "clues": [
            "Single pass solution",
            "Track minimum and maximum relationship",
            "Two positions moving through array",
        ],
        "complexity": "O(n)",
    },
    {
        "id": "binary-search",
        "title": "Binary Search",
        "prompt": "Given a sorted array of integers nums and a target value, return the index of the target if it exists, otherwise return -1.",
        "pattern": "Binary Search",
        "choices": ["Greedy", "Two Pointers", "Binary Search", "Breadth First Search"],
        "explanation": "Since the array is sorted, repeatedly dividing the search space in half gives an efficient logarithmic-time solution.",
        "clues": [
            "Input is sorted",
            "Eliminate half the search space",
            "Looking for logarithmic runtime",
        ],
        "complexity": "O(log n)",
    },
    {
        "id": "maximum-depth-binary-tree",
        "title": "Maximum Depth of Binary Tree",
        "prompt": "Given the root of a binary tree, return its maximum depth.",
        "pattern": "Depth First Search",
        "choices": ["Sliding Window", "Depth First Search", "Prefix Sum", "Union Find"],
        "explanation": "DFS recursively explores each branch to compute the longest path from root to leaf.",
        "clues": [
            "Tree traversal problem",
            "Recursive structure",
            "Need to explore all branches",
        ],
        "complexity": "O(n)",
    },
    {
        "id": "climbing-stairs",
        "title": "Climbing Stairs",
        "prompt": "You are climbing a staircase. It takes n steps to reach the top. Each time you can climb either 1 or 2 steps. Return the number of distinct ways to climb to the top.",
        "pattern": "Dynamic Programming",
        "choices": ["Dynamic Programming", "Binary Search", "Greedy", "Stack"],
        "explanation": "The number of ways to reach step n depends on the solutions to smaller subproblems: n-1 and n-2.",
        "clues": [
            "Repeated subproblems",
            "Build solution from previous states",
            "Fibonacci-like recurrence",
        ],
        "complexity": "O(n)",
    },
    {
        "id": "contains-duplicate",
        "title": "Contains Duplicate",
        "prompt": "Given an integer array nums, return true if any value appears at least twice in the array, and return false if every element is distinct.",
        "pattern": "Hash Map",
        "choices": ["Hash Map", "Two Pointers", "Binary Search", "Dynamic Programming"],
        "explanation": "Insert each element into a hash set; if you see one that's already there, you've found a duplicate.",
        "clues": [
            "Need to detect repeats quickly",
            "Order doesn't matter",
            "O(1) lookup is the unlock",
        ],
        "complexity": "O(n)",
    },
    {
        "id": "valid-anagram",
        "title": "Valid Anagram",
        "prompt": "Given two strings s and t, return true if t is an anagram of s, and false otherwise.",
        "pattern": "Hash Map",
        "choices": ["Hash Map", "Sliding Window", "Two Pointers", "Sorting"],
        "explanation": "Count character frequencies in both strings; they're anagrams if and only if the counts match.",
        "clues": [
            "Comparing character frequencies",
            "Order independent",
            "Counts must match exactly",
        ],
        "complexity": "O(n)",
    },
    {
        "id": "group-anagrams",
        "title": "Group Anagrams",
        "prompt": "Given an array of strings, group the anagrams together. You can return the answer in any order.",
        "pattern": "Hash Map",
        "choices": ["Hash Map", "Trie", "Sorting", "Backtracking"],
        "explanation": "Use a canonical key (sorted string or character count tuple) for each word, then group words sharing the same key in a hash map.",
        "clues": [
            "Group by a canonical form",
            "Need to identify equivalence classes",
            "Hash by character signature",
        ],
        "complexity": "O(n * k)",
    },
    {
        "id": "top-k-frequent",
        "title": "Top K Frequent Elements",
        "prompt": "Given an integer array nums and an integer k, return the k most frequent elements.",
        "pattern": "Heap",
        "choices": ["Heap", "Hash Map", "Binary Search", "Sorting"],
        "explanation": "Count frequencies with a hash map, then use a heap (or bucket sort) to extract the top k by count.",
        "clues": [
            "Asking for top-k of something",
            "Frequency count + ordering",
            "Heap gives O(n log k)",
        ],
        "complexity": "O(n log k)",
    },
    {
        "id": "product-except-self",
        "title": "Product of Array Except Self",
        "prompt": "Given an integer array nums, return an array such that answer[i] is the product of all elements of nums except nums[i]. Solve without using division.",
        "pattern": "Prefix Sum",
        "choices": ["Prefix Sum", "Two Pointers", "Sliding Window", "Dynamic Programming"],
        "explanation": "Build prefix products from the left and suffix products from the right; multiply them at each index.",
        "clues": [
            "Cumulative product on each side",
            "No division allowed",
            "Two-pass O(n) solution",
        ],
        "complexity": "O(n)",
    },
    {
        "id": "valid-sudoku",
        "title": "Valid Sudoku",
        "prompt": "Determine if a 9x9 Sudoku board is valid. Only filled cells need to be checked according to standard Sudoku rules.",
        "pattern": "Hash Map",
        "choices": ["Hash Map", "Backtracking", "Depth First Search", "Bit Manipulation"],
        "explanation": "Track seen digits in each row, column, and 3x3 subgrid using hash sets, returning false on any duplicate.",
        "clues": [
            "Track seen values in groups",
            "Multiple constraints simultaneously",
            "Set membership per row/col/box",
        ],
        "complexity": "O(1)",
    },
    {
        "id": "longest-consecutive",
        "title": "Longest Consecutive Sequence",
        "prompt": "Given an unsorted array of integers, return the length of the longest consecutive elements sequence. The algorithm must run in O(n) time.",
        "pattern": "Hash Map",
        "choices": ["Hash Map", "Sorting", "Union Find", "Sliding Window"],
        "explanation": "Put all numbers in a hash set, then for each number that has no predecessor, count how far the consecutive run extends.",
        "clues": [
            "Need O(n) so sorting is out",
            "Detect run starts efficiently",
            "Constant-time membership check",
        ],
        "complexity": "O(n)",
    },
    {
        "id": "encode-decode-strings",
        "title": "Encode and Decode Strings",
        "prompt": "Design an algorithm to encode a list of strings to a single string and decode it back to the original list.",
        "pattern": "Array",
        "choices": ["Array", "Hash Map", "Stack", "Trie"],
        "explanation": "Prefix each string with its length and a delimiter; on decode, parse the length, then read that many characters.",
        "clues": [
            "Need a self-describing format",
            "Length-prefix is delimiter-safe",
            "Linear scan to decode",
        ],
        "complexity": "O(n)",
    },
    {
        "id": "valid-palindrome",
        "title": "Valid Palindrome",
        "prompt": "Given a string s, return true if it is a palindrome considering only alphanumeric characters and ignoring case.",
        "pattern": "Two Pointers",
        "choices": ["Two Pointers", "Stack", "Sliding Window", "Hash Map"],
        "explanation": "Move pointers from both ends inward, skipping non-alphanumeric characters and comparing the rest.",
        "clues": [
            "Comparing from both ends",
            "Symmetric problem",
            "In-place, no extra string needed",
        ],
        "complexity": "O(n)",
    },
    {
        "id": "two-sum-ii",
        "title": "Two Sum II - Input Array Is Sorted",
        "prompt": "Given a 1-indexed sorted array of integers, find two numbers that add up to a target. Return the 1-based indices.",
        "pattern": "Two Pointers",
        "choices": ["Two Pointers", "Hash Map", "Binary Search", "Sliding Window"],
        "explanation": "With a sorted input, use left/right pointers. If the sum is too small, move left up; if too big, move right down.",
        "clues": [
            "Input is already sorted",
            "Symmetric pointer movement",
            "Constant extra space",
        ],
        "complexity": "O(n)",
    },
    {
        "id": "3sum",
        "title": "3Sum",
        "prompt": "Given an integer array nums, return all unique triplets such that nums[i] + nums[j] + nums[k] = 0.",
        "pattern": "Two Pointers",
        "choices": ["Two Pointers", "Hash Map", "Backtracking", "Dynamic Programming"],
        "explanation": "Sort the array, fix one number, then use two pointers on the remaining range to find pairs that sum to its negation.",
        "clues": [
            "Reduce to a sub-problem after fixing one value",
            "Sorting unlocks two-pointer scan",
            "Skip duplicates to dedupe",
        ],
        "complexity": "O(n^2)",
    },
    {
        "id": "container-water",
        "title": "Container With Most Water",
        "prompt": "Given n non-negative integers representing heights, find two lines that together with the x-axis form a container holding the most water.",
        "pattern": "Two Pointers",
        "choices": ["Two Pointers", "Dynamic Programming", "Greedy", "Sliding Window"],
        "explanation": "Place pointers at both ends. Move the shorter side inward each step — only it can constrain the area.",
        "clues": [
            "Maximum over all pairs",
            "Greedy pointer move based on bottleneck",
            "Width shrinks monotonically",
        ],
        "complexity": "O(n)",
    },
    {
        "id": "trapping-rain-water",
        "title": "Trapping Rain Water",
        "prompt": "Given n non-negative integers representing an elevation map, compute how much water it can trap after raining.",
        "pattern": "Two Pointers",
        "choices": ["Two Pointers", "Stack", "Dynamic Programming", "Prefix Sum"],
        "explanation": "Two pointers from each end track max heights; the side with the lower max determines trapped water at that step.",
        "clues": [
            "Trapped water depends on both sides",
            "Min of two maxes minus current",
            "Single linear pass possible",
        ],
        "complexity": "O(n)",
    },
    {
        "id": "longest-substring-without-repeating",
        "title": "Longest Substring Without Repeating Characters",
        "prompt": "Given a string s, find the length of the longest substring without repeating characters.",
        "pattern": "Sliding Window",
        "choices": ["Sliding Window", "Hash Map", "Two Pointers", "Dynamic Programming"],
        "explanation": "Expand a window to the right, track seen characters in a set; on a duplicate, shrink from the left until the duplicate is removed.",
        "clues": [
            "Contiguous substring with constraint",
            "Window grows and shrinks",
            "Set tracks current window",
        ],
        "complexity": "O(n)",
    },
    {
        "id": "longest-repeating-character-replacement",
        "title": "Longest Repeating Character Replacement",
        "prompt": "You are given a string s and an integer k. Replace at most k characters with any letter to make the longest substring of one repeating character. Return that length.",
        "pattern": "Sliding Window",
        "choices": ["Sliding Window", "Dynamic Programming", "Greedy", "Two Pointers"],
        "explanation": "Slide a window where (window length - count of most frequent char) <= k. Shrink when it exceeds, expand otherwise.",
        "clues": [
            "Window with a budget for changes",
            "Track max char frequency in window",
            "Constraint based on freq vs window size",
        ],
        "complexity": "O(n)",
    },
    {
        "id": "permutation-string",
        "title": "Permutation in String",
        "prompt": "Given two strings s1 and s2, return true if s2 contains a permutation of s1.",
        "pattern": "Sliding Window",
        "choices": ["Sliding Window", "Hash Map", "Backtracking", "Two Pointers"],
        "explanation": "Maintain a fixed-size sliding window over s2 of length len(s1) and compare character counts to s1.",
        "clues": [
            "Fixed-size window",
            "Character count comparison",
            "Order doesn't matter, just frequencies",
        ],
        "complexity": "O(n)",
    },
    {
        "id": "minimum-window-substring",
        "title": "Minimum Window Substring",
        "prompt": "Given strings s and t, return the minimum window in s that contains every character (with multiplicity) of t.",
        "pattern": "Sliding Window",
        "choices": ["Sliding Window", "Hash Map", "Two Pointers", "Dynamic Programming"],
        "explanation": "Expand the window until it covers all needed characters, then contract from the left while it still covers them, tracking the minimum.",
        "clues": [
            "Minimum-length contiguous range",
            "Expand-then-contract window",
            "Tracking unmet character requirements",
        ],
        "complexity": "O(n)",
    },
    {
        "id": "sliding-window-maximum",
        "title": "Sliding Window Maximum",
        "prompt": "Given an array nums and an integer k, return an array of the maximum value in each sliding window of size k.",
        "pattern": "Monotonic Deque",
        "choices": ["Monotonic Deque", "Heap", "Sliding Window", "Dynamic Programming"],
        "explanation": "Maintain a monotonic decreasing deque of indices; the front always holds the current window's max.",
        "clues": [
            "Need fast access to max as window moves",
            "Deque keeps candidates ordered",
            "Pop stale indices from front",
        ],
        "complexity": "O(n)",
    },
    {
        "id": "valid-parentheses",
        "title": "Valid Parentheses",
        "prompt": "Given a string of brackets, determine whether the brackets are matched and properly nested.",
        "pattern": "Stack",
        "choices": ["Stack", "Hash Map", "Recursion", "Greedy"],
        "explanation": "Push opening brackets onto a stack; on a closing bracket, check it matches the top.",
        "clues": [
            "Most-recent-unmatched pattern",
            "LIFO behavior",
            "Match by type",
        ],
        "complexity": "O(n)",
    },
    {
        "id": "min-stack",
        "title": "Min Stack",
        "prompt": "Design a stack that supports push, pop, top, and retrieving the minimum element in constant time.",
        "pattern": "Stack",
        "choices": ["Stack", "Heap", "Hash Map", "Linked List"],
        "explanation": "Maintain an auxiliary stack that records the running minimum at each push, mirroring the main stack's height.",
        "clues": [
            "Constant-time min query",
            "Two parallel stacks",
            "Min depends on stack history",
        ],
        "complexity": "O(1)",
    },
    {
        "id": "evaluate-rpn",
        "title": "Evaluate Reverse Polish Notation",
        "prompt": "Evaluate an arithmetic expression in Reverse Polish Notation given as a list of tokens.",
        "pattern": "Stack",
        "choices": ["Stack", "Recursion", "Tree", "Greedy"],
        "explanation": "Push numbers, and on each operator pop two operands, apply, and push the result.",
        "clues": [
            "Postfix expressions",
            "LIFO operand order",
            "Sequential token consumption",
        ],
        "complexity": "O(n)",
    },
    {
        "id": "generate-parentheses",
        "title": "Generate Parentheses",
        "prompt": "Given n, generate all combinations of n pairs of well-formed parentheses.",
        "pattern": "Backtracking",
        "choices": ["Backtracking", "Dynamic Programming", "Stack", "Recursion"],
        "explanation": "Recursively build strings, adding '(' if open count < n and ')' if close count < open count.",
        "clues": [
            "Generate all valid combinations",
            "Constraints at each step",
            "Tree of choices with pruning",
        ],
        "complexity": "O(4^n / sqrt(n))",
    },
    {
        "id": "daily-temperatures",
        "title": "Daily Temperatures",
        "prompt": "Given an array of daily temperatures, return how many days you have to wait until a warmer temperature for each day.",
        "pattern": "Monotonic Stack",
        "choices": ["Monotonic Stack", "Stack", "Two Pointers", "Dynamic Programming"],
        "explanation": "Maintain a decreasing stack of indices; whenever the current temperature exceeds the top, pop and record the index difference.",
        "clues": [
            "Next greater element pattern",
            "Stack of pending items",
            "Resolve later",
        ],
        "complexity": "O(n)",
    },
    {
        "id": "car-fleet",
        "title": "Car Fleet",
        "prompt": "Given target distance, positions and speeds of cars heading there, return the number of car fleets that arrive at the target.",
        "pattern": "Stack",
        "choices": ["Stack", "Greedy", "Sorting", "Two Pointers"],
        "explanation": "Sort by start position descending, compute time-to-target. Use a stack: a car merges with the fleet ahead if its time is no greater.",
        "clues": [
            "Order matters by position",
            "Compare arrival times sequentially",
            "Stack tracks active fleets",
        ],
        "complexity": "O(n log n)",
    },
    {
        "id": "search-2d-matrix",
        "title": "Search a 2D Matrix",
        "prompt": "Given a m x n matrix sorted row-wise and column-wise, search for a target value.",
        "pattern": "Binary Search",
        "choices": ["Binary Search", "Two Pointers", "Depth First Search", "Hash Map"],
        "explanation": "Treat the matrix as a flattened sorted array and binary-search on the virtual index, mapping back with row=mid/n, col=mid%n.",
        "clues": [
            "Sorted in 2D",
            "Logarithmic time hint",
            "Index math collapses to 1D",
        ],
        "complexity": "O(log(m*n))",
    },
    {
        "id": "koko-eating-bananas",
        "title": "Koko Eating Bananas",
        "prompt": "Find the minimum eating speed k such that Koko can finish all banana piles within h hours, eating at most k bananas per hour.",
        "pattern": "Binary Search",
        "choices": ["Binary Search", "Greedy", "Heap", "Dynamic Programming"],
        "explanation": "Binary search on the answer (eating speed). For a given speed, simulate to check feasibility.",
        "clues": [
            "Monotonic feasibility",
            "Search over answer range",
            "Check function is fast",
        ],
        "complexity": "O(n log m)",
    },
    {
        "id": "find-min-rotated",
        "title": "Find Minimum in Rotated Sorted Array",
        "prompt": "Given a sorted array that has been rotated at some pivot, find the minimum element.",
        "pattern": "Binary Search",
        "choices": ["Binary Search", "Two Pointers", "Greedy", "Linear Scan"],
        "explanation": "Compare nums[mid] to nums[right]: if smaller, the min is in the left half (inclusive); otherwise it's in the right.",
        "clues": [
            "Rotated sorted property",
            "Logarithmic expected",
            "Compare to right boundary",
        ],
        "complexity": "O(log n)",
    },
    {
        "id": "search-rotated-array",
        "title": "Search in Rotated Sorted Array",
        "prompt": "Given a rotated sorted array and a target, return the target's index, or -1 if not found.",
        "pattern": "Binary Search",
        "choices": ["Binary Search", "Two Pointers", "Hash Map", "Linear Scan"],
        "explanation": "Identify which half is sorted at each step, then check whether the target is in that sorted half.",
        "clues": [
            "Sorted with one rotation",
            "Logarithmic time required",
            "Determine which half is in order",
        ],
        "complexity": "O(log n)",
    },
    {
        "id": "median-two-sorted-arrays",
        "title": "Median of Two Sorted Arrays",
        "prompt": "Given two sorted arrays, find the median of the combined array in O(log(m+n)) time.",
        "pattern": "Binary Search",
        "choices": ["Binary Search", "Two Pointers", "Heap", "Merge Sort"],
        "explanation": "Binary search a partition point in the smaller array such that left halves of both arrays form the lower half of the median split.",
        "clues": [
            "Logarithmic constraint rules out merge",
            "Partition both arrays",
            "Maintain median property across two arrays",
        ],
        "complexity": "O(log(min(m, n)))",
    },
    {
        "id": "reverse-linked-list",
        "title": "Reverse Linked List",
        "prompt": "Given the head of a singly linked list, reverse the list and return the new head.",
        "pattern": "Linked List",
        "choices": ["Linked List", "Stack", "Recursion", "Two Pointers"],
        "explanation": "Iterate while flipping each node's next pointer to its previous; track previous, current, and next pointers.",
        "clues": [
            "Pointer manipulation",
            "In-place reversal possible",
            "Three-pointer dance",
        ],
        "complexity": "O(n)",
    },
    {
        "id": "merge-two-sorted-lists",
        "title": "Merge Two Sorted Lists",
        "prompt": "You are given the heads of two sorted linked lists. Merge them into one sorted list and return its head.",
        "pattern": "Linked List",
        "choices": ["Linked List", "Two Pointers", "Heap", "Recursion"],
        "explanation": "Walk both lists with two pointers, always appending the smaller current node; finally attach any remainder.",
        "clues": [
            "Two sorted inputs",
            "Stitch in order",
            "Dummy node simplifies edges",
        ],
        "complexity": "O(n + m)",
    },
    {
        "id": "reorder-list",
        "title": "Reorder List",
        "prompt": "Given the head of a singly linked list, reorder it as L0, Ln, L1, Ln-1, L2, Ln-2 ...",
        "pattern": "Linked List",
        "choices": ["Linked List", "Stack", "Two Pointers", "Recursion"],
        "explanation": "Find middle with slow/fast pointers, reverse the second half, then weave the two halves together.",
        "clues": [
            "Three-step composition",
            "Middle finding",
            "Reverse and interleave",
        ],
        "complexity": "O(n)",
    },
    {
        "id": "remove-nth-node",
        "title": "Remove Nth Node From End of List",
        "prompt": "Given the head of a linked list, remove the nth node from the end and return the head.",
        "pattern": "Two Pointers",
        "choices": ["Two Pointers", "Linked List", "Stack", "Recursion"],
        "explanation": "Advance a fast pointer n steps ahead, then move both fast and slow until fast hits the end. Slow now points just before the target.",
        "clues": [
            "Single-pass requirement",
            "Gap-of-n pointers",
            "Edge case at head",
        ],
        "complexity": "O(n)",
    },
    {
        "id": "linked-list-cycle",
        "title": "Linked List Cycle",
        "prompt": "Given the head of a linked list, determine if it contains a cycle.",
        "pattern": "Fast and Slow Pointers",
        "choices": ["Fast and Slow Pointers", "Hash Map", "Stack", "Recursion"],
        "explanation": "Two pointers move at different speeds. If a cycle exists they meet; otherwise the fast pointer reaches null.",
        "clues": [
            "Detecting a loop",
            "Constant extra space",
            "Tortoise and hare",
        ],
        "complexity": "O(n)",
    },
    {
        "id": "find-middle-linked-list",
        "title": "Middle of the Linked List",
        "prompt": "Given the head of a singly linked list, return the middle node. If the list has even length, return the second middle.",
        "pattern": "Fast and Slow Pointers",
        "choices": ["Fast and Slow Pointers", "Two Pointers", "Linked List", "Stack"],
        "explanation": "Move slow by one and fast by two; when fast reaches the end, slow is at the middle.",
        "clues": [
            "Find middle in one pass",
            "No length precomputation",
            "Speed differential",
        ],
        "complexity": "O(n)",
    },
    {
        "id": "copy-list-random-pointer",
        "title": "Copy List with Random Pointer",
        "prompt": "A linked list has nodes with a value and a random pointer. Make a deep copy of the list.",
        "pattern": "Hash Map",
        "choices": ["Hash Map", "Linked List", "Recursion", "Two Pointers"],
        "explanation": "Map each original node to its copy in a hash table, then wire next and random pointers using the map.",
        "clues": [
            "Need to mirror random links",
            "Two passes over the list",
            "Original-to-copy mapping",
        ],
        "complexity": "O(n)",
    },
    {
        "id": "invert-binary-tree",
        "title": "Invert Binary Tree",
        "prompt": "Given the root of a binary tree, invert it (swap every left/right pair).",
        "pattern": "Depth First Search",
        "choices": ["Depth First Search", "Breadth First Search", "Recursion", "Stack"],
        "explanation": "Recursively swap the left and right children at each node.",
        "clues": [
            "Per-node transformation",
            "Tree recursion",
            "Symmetric swap",
        ],
        "complexity": "O(n)",
    },
    {
        "id": "diameter-binary-tree",
        "title": "Diameter of Binary Tree",
        "prompt": "Given the root of a binary tree, return the length of the longest path between any two nodes.",
        "pattern": "Depth First Search",
        "choices": ["Depth First Search", "Breadth First Search", "Dynamic Programming", "Greedy"],
        "explanation": "Post-order DFS returning subtree height while updating a global max for left height + right height at each node.",
        "clues": [
            "Path may not pass through root",
            "Combine left and right heights",
            "Track global maximum",
        ],
        "complexity": "O(n)",
    },
    {
        "id": "balanced-binary-tree",
        "title": "Balanced Binary Tree",
        "prompt": "Given a binary tree, determine if it is height-balanced (the depth of the two subtrees of every node never differs by more than one).",
        "pattern": "Depth First Search",
        "choices": ["Depth First Search", "Breadth First Search", "Recursion", "Greedy"],
        "explanation": "Post-order DFS returning height; bubble up a sentinel if any subtree is unbalanced.",
        "clues": [
            "Per-node invariant",
            "Height + balance check together",
            "Early-out signal",
        ],
        "complexity": "O(n)",
    },
    {
        "id": "same-tree",
        "title": "Same Tree",
        "prompt": "Given the roots of two binary trees, check whether they are structurally identical and have the same node values.",
        "pattern": "Depth First Search",
        "choices": ["Depth First Search", "Breadth First Search", "Recursion", "Stack"],
        "explanation": "Recursively compare nodes pairwise: equal values and recursively-equal subtrees.",
        "clues": [
            "Mirror traversal of two trees",
            "Compare structure and values",
            "Base cases on null",
        ],
        "complexity": "O(n)",
    },
    {
        "id": "subtree-of-another-tree",
        "title": "Subtree of Another Tree",
        "prompt": "Given two trees s and t, return true if t is a subtree of s.",
        "pattern": "Depth First Search",
        "choices": ["Depth First Search", "Breadth First Search", "Trie", "Hash Map"],
        "explanation": "At each node of s, check if the subtree rooted there equals t using a same-tree comparison.",
        "clues": [
            "Combine traversal with sub-check",
            "Reuse same-tree primitive",
            "Tree-in-tree pattern",
        ],
        "complexity": "O(n*m)",
    },
    {
        "id": "lowest-common-ancestor-bst",
        "title": "Lowest Common Ancestor of a BST",
        "prompt": "Given a BST and two nodes p and q, return their lowest common ancestor.",
        "pattern": "Binary Search",
        "choices": ["Binary Search", "Depth First Search", "Recursion", "Hash Map"],
        "explanation": "Walk from the root: if both p and q are smaller, go left; if larger, go right; otherwise the current node is the LCA.",
        "clues": [
            "BST ordering speeds it up",
            "Decide direction by value",
            "First split point is the LCA",
        ],
        "complexity": "O(h)",
    },
    {
        "id": "level-order-traversal",
        "title": "Binary Tree Level Order Traversal",
        "prompt": "Given the root of a binary tree, return the level-order traversal of its nodes' values.",
        "pattern": "Breadth First Search",
        "choices": ["Breadth First Search", "Depth First Search", "Stack", "Recursion"],
        "explanation": "BFS with a queue, processing one level at a time and grouping nodes by level.",
        "clues": [
            "Level-by-level visit",
            "Queue-based traversal",
            "Need to know level boundaries",
        ],
        "complexity": "O(n)",
    },
    {
        "id": "right-side-view",
        "title": "Binary Tree Right Side View",
        "prompt": "Given the root of a binary tree, return the values of the nodes you can see from the right side, ordered top to bottom.",
        "pattern": "Breadth First Search",
        "choices": ["Breadth First Search", "Depth First Search", "Stack", "Recursion"],
        "explanation": "BFS by level; record the last value of each level. Equivalently, DFS keeping the first node visited at each depth on right-first traversal.",
        "clues": [
            "Per-level rightmost",
            "Level-order traversal",
            "Track max depth seen",
        ],
        "complexity": "O(n)",
    },
    {
        "id": "count-good-nodes",
        "title": "Count Good Nodes in Binary Tree",
        "prompt": "A node is good if no node on the path from root to it has a greater value. Count good nodes.",
        "pattern": "Depth First Search",
        "choices": ["Depth First Search", "Breadth First Search", "Greedy", "Dynamic Programming"],
        "explanation": "DFS while passing down the running max along the path; increment when the current node is at least the running max.",
        "clues": [
            "Path-dependent property",
            "Carry state through recursion",
            "Compare against ancestors",
        ],
        "complexity": "O(n)",
    },
    {
        "id": "validate-bst",
        "title": "Validate Binary Search Tree",
        "prompt": "Given the root of a binary tree, determine if it is a valid binary search tree.",
        "pattern": "Depth First Search",
        "choices": ["Depth First Search", "Breadth First Search", "Stack", "Greedy"],
        "explanation": "DFS with running min and max bounds; at each node, ensure value lies in (low, high), then recurse with tightened bounds.",
        "clues": [
            "Recursive constraints",
            "Bounds tighten down the tree",
            "Validate per-subtree",
        ],
        "complexity": "O(n)",
    },
    {
        "id": "kth-smallest-bst",
        "title": "Kth Smallest Element in a BST",
        "prompt": "Given the root of a BST and integer k, return the kth smallest element.",
        "pattern": "Depth First Search",
        "choices": ["Depth First Search", "Heap", "Breadth First Search", "Binary Search"],
        "explanation": "In-order traversal yields values in sorted order; stop when you've visited k nodes.",
        "clues": [
            "BST in-order is sorted",
            "Early exit at k",
            "Iterative or recursive",
        ],
        "complexity": "O(h + k)",
    },
    {
        "id": "construct-tree-preorder-inorder",
        "title": "Construct Binary Tree from Preorder and Inorder Traversal",
        "prompt": "Given preorder and inorder traversal arrays, reconstruct the binary tree.",
        "pattern": "Depth First Search",
        "choices": ["Depth First Search", "Recursion", "Hash Map", "Dynamic Programming"],
        "explanation": "First preorder element is the root; locate it in inorder to split left and right subtrees, then recurse.",
        "clues": [
            "Preorder gives root order",
            "Inorder splits subtrees",
            "Hash inorder indices",
        ],
        "complexity": "O(n)",
    },
    {
        "id": "implement-trie",
        "title": "Implement Trie (Prefix Tree)",
        "prompt": "Implement a trie supporting insert, search, and startsWith operations.",
        "pattern": "Trie",
        "choices": ["Trie", "Hash Map", "Tree", "Recursion"],
        "explanation": "Each trie node holds children keyed by character and an end-of-word flag; traverse character by character.",
        "clues": [
            "Prefix sharing among words",
            "Character-keyed children",
            "End-of-word marker",
        ],
        "complexity": "O(L)",
    },
    {
        "id": "design-add-search-words",
        "title": "Design Add and Search Words",
        "prompt": "Design a data structure that supports adding words and searching with literals or '.' wildcards.",
        "pattern": "Trie",
        "choices": ["Trie", "Hash Map", "Backtracking", "Recursion"],
        "explanation": "Trie for storage; on '.', branch into all children (DFS) and continue.",
        "clues": [
            "Wildcard search",
            "Trie + DFS hybrid",
            "Per-character branching",
        ],
        "complexity": "O(L * 26^k)",
    },
    {
        "id": "kth-largest-element",
        "title": "Kth Largest Element in an Array",
        "prompt": "Given an integer array nums and integer k, return the kth largest element.",
        "pattern": "Heap",
        "choices": ["Heap", "Quickselect", "Sorting", "Binary Search"],
        "explanation": "Maintain a min-heap of size k; the root is the answer when finished.",
        "clues": [
            "Top-k by ordering",
            "Heap of size k",
            "Stream-friendly approach",
        ],
        "complexity": "O(n log k)",
    },
    {
        "id": "last-stone-weight",
        "title": "Last Stone Weight",
        "prompt": "Given an array of stone weights, repeatedly smash the two heaviest stones together; return the last remaining weight.",
        "pattern": "Heap",
        "choices": ["Heap", "Sorting", "Greedy", "Priority Queue"],
        "explanation": "Use a max-heap. Each step pops two largest, pushes the difference if non-zero.",
        "clues": [
            "Always need the largest two",
            "Repeated max extraction",
            "Greedy simulation",
        ],
        "complexity": "O(n log n)",
    },
    {
        "id": "k-closest-points-origin",
        "title": "K Closest Points to Origin",
        "prompt": "Given an array of points and integer k, return the k closest points to the origin.",
        "pattern": "Heap",
        "choices": ["Heap", "Quickselect", "Sorting", "Binary Search"],
        "explanation": "Use a max-heap of size k by distance; pop when oversized so the heap retains the k closest seen so far.",
        "clues": [
            "Top-k by distance",
            "Heap of size k",
            "No need to sort all",
        ],
        "complexity": "O(n log k)",
    },
    {
        "id": "task-scheduler",
        "title": "Task Scheduler",
        "prompt": "Given tasks and a cooldown n, return the minimum number of intervals to finish all tasks.",
        "pattern": "Heap",
        "choices": ["Heap", "Greedy", "Math", "Dynamic Programming"],
        "explanation": "Greedy with a max-heap: at each step pick the most-frequent remaining task; idle if all in cooldown.",
        "clues": [
            "Frequency-driven scheduling",
            "Cooldown queue",
            "Most-frequent constrained",
        ],
        "complexity": "O(n log n)",
    },
    {
        "id": "find-median-data-stream",
        "title": "Find Median from Data Stream",
        "prompt": "Design a class that supports adding numbers and returning the median of all added numbers.",
        "pattern": "Heap",
        "choices": ["Heap", "Sorting", "Binary Search", "Hash Map"],
        "explanation": "Maintain a max-heap of the lower half and a min-heap of the upper half; rebalance after each insert.",
        "clues": [
            "Streaming median",
            "Two-heap split",
            "Constant-time peek",
        ],
        "complexity": "O(log n) per add",
    },
    {
        "id": "subsets",
        "title": "Subsets",
        "prompt": "Given an integer array of unique elements, return all possible subsets.",
        "pattern": "Backtracking",
        "choices": ["Backtracking", "Bit Manipulation", "Recursion", "Dynamic Programming"],
        "explanation": "DFS with include/exclude branches at each index; collect path on every recursive call.",
        "clues": [
            "Power set generation",
            "Binary include decision",
            "Output 2^n subsets",
        ],
        "complexity": "O(n * 2^n)",
    },
    {
        "id": "combination-sum",
        "title": "Combination Sum",
        "prompt": "Given an array of distinct integers and a target, return all unique combinations that sum to target. The same number may be chosen unlimited times.",
        "pattern": "Backtracking",
        "choices": ["Backtracking", "Dynamic Programming", "Greedy", "Recursion"],
        "explanation": "Recurse with current index and remaining target; at each step include current (allowing reuse) or move to next.",
        "clues": [
            "Unbounded reuse",
            "Subset-sum variant",
            "Avoid duplicate combos via index",
        ],
        "complexity": "O(2^t)",
    },
    {
        "id": "permutations",
        "title": "Permutations",
        "prompt": "Given an array of distinct integers, return all possible permutations.",
        "pattern": "Backtracking",
        "choices": ["Backtracking", "Recursion", "Dynamic Programming", "Greedy"],
        "explanation": "DFS picking an unused element at each level; restore the choice on return.",
        "clues": [
            "All orderings",
            "Used set tracks state",
            "n! results",
        ],
        "complexity": "O(n * n!)",
    },
    {
        "id": "subsets-ii",
        "title": "Subsets II",
        "prompt": "Given an integer array (may contain duplicates), return all possible unique subsets.",
        "pattern": "Backtracking",
        "choices": ["Backtracking", "Bit Manipulation", "Hash Map", "Sorting"],
        "explanation": "Sort the input, then DFS skipping duplicates at the same recursion depth to avoid producing repeated subsets.",
        "clues": [
            "Duplicates require pruning",
            "Sort to group equals",
            "Skip-on-same-level rule",
        ],
        "complexity": "O(n * 2^n)",
    },
    {
        "id": "combination-sum-ii",
        "title": "Combination Sum II",
        "prompt": "Given a candidate array (with duplicates) and a target, find unique combinations that sum to target. Each candidate may be used at most once.",
        "pattern": "Backtracking",
        "choices": ["Backtracking", "Dynamic Programming", "Hash Map", "Recursion"],
        "explanation": "Sort, then DFS advancing index by 1 and skipping equal values on the same recursion depth.",
        "clues": [
            "Single use per element",
            "Skip duplicates at level",
            "Target reduction",
        ],
        "complexity": "O(2^n)",
    },
    {
        "id": "word-search",
        "title": "Word Search",
        "prompt": "Given a 2D board and a word, return true if the word can be constructed from adjacent letters in the board (no cell reused).",
        "pattern": "Backtracking",
        "choices": ["Backtracking", "Depth First Search", "Trie", "Dynamic Programming"],
        "explanation": "DFS from each cell, marking visited cells temporarily; backtrack when the path fails.",
        "clues": [
            "Grid path search",
            "Try then undo",
            "No revisit per attempt",
        ],
        "complexity": "O(m*n*4^L)",
    },
    {
        "id": "palindrome-partitioning",
        "title": "Palindrome Partitioning",
        "prompt": "Given a string s, partition it such that every substring is a palindrome; return all such partitions.",
        "pattern": "Backtracking",
        "choices": ["Backtracking", "Dynamic Programming", "Recursion", "Greedy"],
        "explanation": "DFS choosing each prefix that is a palindrome, then recursing on the suffix.",
        "clues": [
            "Try all valid splits",
            "Check palindrome at each cut",
            "Recursive build of partitions",
        ],
        "complexity": "O(n * 2^n)",
    },
    {
        "id": "number-of-islands",
        "title": "Number of Islands",
        "prompt": "Given a 2D grid of '1's (land) and '0's (water), count the number of islands.",
        "pattern": "Depth First Search",
        "choices": ["Depth First Search", "Breadth First Search", "Union Find", "Backtracking"],
        "explanation": "Scan the grid; on each unvisited '1', DFS to flood-fill all connected land, incrementing the island count.",
        "clues": [
            "Connected components in grid",
            "Flood fill",
            "Mark visited as you go",
        ],
        "complexity": "O(m*n)",
    },
    {
        "id": "clone-graph",
        "title": "Clone Graph",
        "prompt": "Given a reference to a node in a connected undirected graph, return a deep copy of the graph.",
        "pattern": "Depth First Search",
        "choices": ["Depth First Search", "Breadth First Search", "Hash Map", "Recursion"],
        "explanation": "DFS while keeping a hash map from original nodes to their clones to avoid revisiting and to wire neighbors.",
        "clues": [
            "Avoid infinite recursion in cycles",
            "Mapping old to new",
            "Visit each node once",
        ],
        "complexity": "O(V + E)",
    },
    {
        "id": "max-area-of-island",
        "title": "Max Area of Island",
        "prompt": "Given a 2D grid of 0s and 1s, return the maximum area of an island (connected 1s).",
        "pattern": "Depth First Search",
        "choices": ["Depth First Search", "Breadth First Search", "Union Find", "Dynamic Programming"],
        "explanation": "DFS each unvisited land cell, summing area; track the maximum across components.",
        "clues": [
            "Connected component size",
            "Flood fill with counter",
            "Mark visited cells",
        ],
        "complexity": "O(m*n)",
    },
    {
        "id": "pacific-atlantic-water",
        "title": "Pacific Atlantic Water Flow",
        "prompt": "Given a matrix of heights with the Pacific along the top/left and Atlantic along the bottom/right, find cells whose water can flow to both oceans.",
        "pattern": "Depth First Search",
        "choices": ["Depth First Search", "Breadth First Search", "Union Find", "Dynamic Programming"],
        "explanation": "Reverse DFS from each ocean's borders, marking cells reachable; the answer is the intersection.",
        "clues": [
            "Reverse flow trick",
            "Two reachability sets",
            "Intersect ocean fronts",
        ],
        "complexity": "O(m*n)",
    },
    {
        "id": "surrounded-regions",
        "title": "Surrounded Regions",
        "prompt": "Given a board with X and O, capture all regions of O that are completely surrounded by X.",
        "pattern": "Depth First Search",
        "choices": ["Depth First Search", "Breadth First Search", "Union Find", "Greedy"],
        "explanation": "Mark border-connected O regions as safe via DFS, then flip remaining O to X and unmark safe back to O.",
        "clues": [
            "Border-connected immunity",
            "Two-phase flipping",
            "Avoid converting border-touching",
        ],
        "complexity": "O(m*n)",
    },
    {
        "id": "rotting-oranges",
        "title": "Rotting Oranges",
        "prompt": "Given a grid where 0=empty, 1=fresh orange, 2=rotten, return the minimum number of minutes until no fresh oranges remain (or -1).",
        "pattern": "Breadth First Search",
        "choices": ["Breadth First Search", "Depth First Search", "Dynamic Programming", "Union Find"],
        "explanation": "Multi-source BFS starting from all rotten oranges; track levels until all fresh are infected.",
        "clues": [
            "Spreading infection",
            "Multi-source BFS",
            "Level = minutes",
        ],
        "complexity": "O(m*n)",
    },
    {
        "id": "walls-and-gates",
        "title": "Walls and Gates",
        "prompt": "Given a grid with walls, gates, and empty rooms, fill each empty room with the distance to its nearest gate.",
        "pattern": "Breadth First Search",
        "choices": ["Breadth First Search", "Depth First Search", "Dynamic Programming", "Greedy"],
        "explanation": "Multi-source BFS from all gates simultaneously, expanding in layers and writing distances.",
        "clues": [
            "Multiple sources",
            "Shortest distances on grid",
            "Expand by layer",
        ],
        "complexity": "O(m*n)",
    },
    {
        "id": "course-schedule",
        "title": "Course Schedule",
        "prompt": "Given numCourses and prerequisites, determine if you can finish all courses (i.e., the dependency graph has no cycles).",
        "pattern": "Topological Sort",
        "choices": ["Topological Sort", "Depth First Search", "Breadth First Search", "Union Find"],
        "explanation": "Kahn's algorithm (BFS on indegrees) or DFS cycle detection; either works.",
        "clues": [
            "Cycle detection in DAG",
            "Dependency ordering",
            "Indegree-based scheduling",
        ],
        "complexity": "O(V + E)",
    },
    {
        "id": "course-schedule-ii",
        "title": "Course Schedule II",
        "prompt": "Return any valid order to finish all courses given prerequisites, or empty if impossible.",
        "pattern": "Topological Sort",
        "choices": ["Topological Sort", "Depth First Search", "Breadth First Search", "Greedy"],
        "explanation": "Topological sort via Kahn's algorithm (queue of zero-indegree nodes) or DFS post-order with cycle check.",
        "clues": [
            "Valid linear ordering",
            "DAG required",
            "Output order matters",
        ],
        "complexity": "O(V + E)",
    },
    {
        "id": "redundant-connection",
        "title": "Redundant Connection",
        "prompt": "In a graph that started as a tree, find an edge that can be removed so the graph is again a tree.",
        "pattern": "Union Find",
        "choices": ["Union Find", "Depth First Search", "Breadth First Search", "Topological Sort"],
        "explanation": "Process edges in order; the one that connects two already-unified nodes is the redundant edge.",
        "clues": [
            "Detect cycle by union",
            "Disjoint-set structure",
            "First edge closing a cycle",
        ],
        "complexity": "O(n alpha(n))",
    },
    {
        "id": "number-of-connected-components",
        "title": "Number of Connected Components in an Undirected Graph",
        "prompt": "Given n nodes and a list of edges, return the number of connected components.",
        "pattern": "Union Find",
        "choices": ["Union Find", "Depth First Search", "Breadth First Search", "Topological Sort"],
        "explanation": "Initialize each node in its own component; each successful union reduces component count by 1.",
        "clues": [
            "Component counting",
            "Disjoint sets",
            "Union reduces count",
        ],
        "complexity": "O(n + e)",
    },
    {
        "id": "graph-valid-tree",
        "title": "Graph Valid Tree",
        "prompt": "Given n nodes and a list of undirected edges, determine if they form a valid tree.",
        "pattern": "Union Find",
        "choices": ["Union Find", "Depth First Search", "Breadth First Search", "Topological Sort"],
        "explanation": "A tree has exactly n-1 edges and no cycles; use union-find to detect cycle and check the edge count.",
        "clues": [
            "n-1 edges constraint",
            "No cycles allowed",
            "Connectedness implied",
        ],
        "complexity": "O(n alpha(n))",
    },
    {
        "id": "coin-change",
        "title": "Coin Change",
        "prompt": "Given coin denominations and an amount, return the fewest number of coins to make that amount, or -1 if impossible.",
        "pattern": "Dynamic Programming",
        "choices": ["Dynamic Programming", "Greedy", "Backtracking", "Breadth First Search"],
        "explanation": "Bottom-up DP: dp[a] = 1 + min(dp[a - c]) for each coin c. Greedy fails for irregular denominations.",
        "clues": [
            "Optimal substructure",
            "Greedy is wrong here",
            "Build up from smaller amounts",
        ],
        "complexity": "O(n * amount)",
    },
    {
        "id": "house-robber",
        "title": "House Robber",
        "prompt": "Given an array of non-negative integers representing money in each house, find the max you can rob without robbing two adjacent houses.",
        "pattern": "Dynamic Programming",
        "choices": ["Dynamic Programming", "Greedy", "Recursion", "Backtracking"],
        "explanation": "dp[i] = max(dp[i-1], dp[i-2] + nums[i]); rolling two variables suffices.",
        "clues": [
            "Choice to take or skip",
            "Adjacency constraint",
            "Two-state recurrence",
        ],
        "complexity": "O(n)",
    },
    {
        "id": "house-robber-ii",
        "title": "House Robber II",
        "prompt": "Same as House Robber, but houses are arranged in a circle.",
        "pattern": "Dynamic Programming",
        "choices": ["Dynamic Programming", "Greedy", "Two Pointers", "Recursion"],
        "explanation": "Run the linear House Robber twice: once excluding the first house, once excluding the last; return the max.",
        "clues": [
            "Circular constraint",
            "Two cases",
            "Reuse linear DP",
        ],
        "complexity": "O(n)",
    },
    {
        "id": "longest-palindromic-substring",
        "title": "Longest Palindromic Substring",
        "prompt": "Given a string s, return the longest palindromic substring.",
        "pattern": "Dynamic Programming",
        "choices": ["Dynamic Programming", "Two Pointers", "Sliding Window", "Greedy"],
        "explanation": "Expand around each center (single and double) tracking the longest palindrome found, or use 2D DP.",
        "clues": [
            "Centers and edges",
            "Two cases (odd/even)",
            "Pairwise expansions",
        ],
        "complexity": "O(n^2)",
    },
    {
        "id": "palindromic-substrings",
        "title": "Palindromic Substrings",
        "prompt": "Given a string s, return the number of palindromic substrings in it.",
        "pattern": "Dynamic Programming",
        "choices": ["Dynamic Programming", "Two Pointers", "Greedy", "Hash Map"],
        "explanation": "Expand around each possible center counting all palindromes, or fill a 2D DP table.",
        "clues": [
            "Count all palindromes",
            "Center expansion",
            "Two parities",
        ],
        "complexity": "O(n^2)",
    },
    {
        "id": "decode-ways",
        "title": "Decode Ways",
        "prompt": "A digit string is decoded by mapping 1->A, 2->B, ..., 26->Z. Return the number of ways to decode it.",
        "pattern": "Dynamic Programming",
        "choices": ["Dynamic Programming", "Recursion", "Backtracking", "Greedy"],
        "explanation": "dp[i] = dp[i-1] (if last char is 1-9) + dp[i-2] (if last two form 10-26).",
        "clues": [
            "One-or-two-digit decisions",
            "Watch zero edge cases",
            "Linear DP",
        ],
        "complexity": "O(n)",
    },
    {
        "id": "longest-increasing-subsequence",
        "title": "Longest Increasing Subsequence",
        "prompt": "Given an integer array, return the length of the longest strictly increasing subsequence.",
        "pattern": "Dynamic Programming",
        "choices": ["Dynamic Programming", "Binary Search", "Greedy", "Two Pointers"],
        "explanation": "DP O(n^2) with dp[i] = 1 + max(dp[j] for j<i, nums[j]<nums[i]). Patience-sort style with binary search gives O(n log n).",
        "clues": [
            "Subsequence not subarray",
            "Non-contiguous order",
            "Patience-sort trick",
        ],
        "complexity": "O(n log n)",
    },
    {
        "id": "maximum-product-subarray",
        "title": "Maximum Product Subarray",
        "prompt": "Find the contiguous subarray with the largest product.",
        "pattern": "Dynamic Programming",
        "choices": ["Dynamic Programming", "Sliding Window", "Greedy", "Two Pointers"],
        "explanation": "Track running max and min ending at each index since negatives flip; update global max each step.",
        "clues": [
            "Negatives matter",
            "Track min and max",
            "Linear DP with two states",
        ],
        "complexity": "O(n)",
    },
    {
        "id": "unique-paths",
        "title": "Unique Paths",
        "prompt": "On an m x n grid, count the number of unique paths from top-left to bottom-right moving only down or right.",
        "pattern": "Dynamic Programming",
        "choices": ["Dynamic Programming", "Math", "Backtracking", "Recursion"],
        "explanation": "dp[i][j] = dp[i-1][j] + dp[i][j-1] with first row and column initialized to 1. Equivalently a binomial coefficient.",
        "clues": [
            "Grid-counting",
            "Two move choices",
            "Paths add",
        ],
        "complexity": "O(m*n)",
    },
    {
        "id": "longest-common-subsequence",
        "title": "Longest Common Subsequence",
        "prompt": "Given two strings, return the length of their longest common subsequence.",
        "pattern": "Dynamic Programming",
        "choices": ["Dynamic Programming", "Two Pointers", "Greedy", "Backtracking"],
        "explanation": "2D DP: if chars match, dp[i][j] = dp[i-1][j-1] + 1; else max of dp[i-1][j], dp[i][j-1].",
        "clues": [
            "Two-string matching",
            "Subsequence (not contiguous)",
            "Grid DP",
        ],
        "complexity": "O(m*n)",
    },
    {
        "id": "best-time-stock-cooldown",
        "title": "Best Time to Buy and Sell Stock with Cooldown",
        "prompt": "Find the maximum profit from buying and selling stock with a one-day cooldown after selling.",
        "pattern": "Dynamic Programming",
        "choices": ["Dynamic Programming", "Greedy", "Sliding Window", "Recursion"],
        "explanation": "State machine over hold/sold/cooldown; transition with pre-day's states.",
        "clues": [
            "Multiple states per day",
            "State transitions",
            "Constraint forces a delay",
        ],
        "complexity": "O(n)",
    },
    {
        "id": "coin-change-ii",
        "title": "Coin Change II",
        "prompt": "Given coin denominations and an amount, return the number of distinct combinations that make up the amount.",
        "pattern": "Dynamic Programming",
        "choices": ["Dynamic Programming", "Backtracking", "Greedy", "Recursion"],
        "explanation": "Outer loop over coins, inner loop over amounts; dp[a] += dp[a - coin]. Coin order outside avoids double-counting.",
        "clues": [
            "Combinations not permutations",
            "Loop order matters",
            "Unbounded knapsack",
        ],
        "complexity": "O(n * amount)",
    },
    {
        "id": "target-sum",
        "title": "Target Sum",
        "prompt": "Given an array of integers and a target, count how many ways to assign + or - to each number so the sum equals the target.",
        "pattern": "Dynamic Programming",
        "choices": ["Dynamic Programming", "Backtracking", "Recursion", "Greedy"],
        "explanation": "Reformulate: pick subset summing to (sum + target) / 2; standard subset-sum DP.",
        "clues": [
            "Sign assignment count",
            "Reduce to subset sum",
            "Even-parity check",
        ],
        "complexity": "O(n * sum)",
    },
    {
        "id": "edit-distance",
        "title": "Edit Distance",
        "prompt": "Given two strings, return the minimum number of insert, delete, or replace operations to convert one into the other.",
        "pattern": "Dynamic Programming",
        "choices": ["Dynamic Programming", "Backtracking", "Greedy", "Two Pointers"],
        "explanation": "2D DP where dp[i][j] = dp[i-1][j-1] (if equal) else 1 + min of three neighbors (insert, delete, replace).",
        "clues": [
            "Three op choices",
            "String alignment",
            "Grid DP",
        ],
        "complexity": "O(m*n)",
    },
    {
        "id": "maximum-subarray",
        "title": "Maximum Subarray",
        "prompt": "Given an integer array, find the contiguous subarray with the largest sum.",
        "pattern": "Dynamic Programming",
        "choices": ["Dynamic Programming", "Greedy", "Two Pointers", "Sliding Window"],
        "explanation": "Kadane's algorithm: at each index, current = max(num, current + num); track global max.",
        "clues": [
            "Contiguous and additive",
            "Reset when running sum negative",
            "Linear time",
        ],
        "complexity": "O(n)",
    },
    {
        "id": "jump-game",
        "title": "Jump Game",
        "prompt": "Given an array where each element represents max jump length from that index, determine if you can reach the last index.",
        "pattern": "Greedy",
        "choices": ["Greedy", "Dynamic Programming", "Backtracking", "Breadth First Search"],
        "explanation": "Track the farthest reachable index as you scan; if your current index ever exceeds it, return false.",
        "clues": [
            "Reachability with budget",
            "Single-pass greedy",
            "Track farthest",
        ],
        "complexity": "O(n)",
    },
    {
        "id": "jump-game-ii",
        "title": "Jump Game II",
        "prompt": "Return the minimum number of jumps to reach the last index, assuming you can always reach it.",
        "pattern": "Greedy",
        "choices": ["Greedy", "Dynamic Programming", "Breadth First Search", "Backtracking"],
        "explanation": "BFS-like greedy: track current jump's far edge; once you cross it, increment jump count and extend the edge.",
        "clues": [
            "Min number of moves",
            "Layered traversal",
            "Greedy extension of frontier",
        ],
        "complexity": "O(n)",
    },
    {
        "id": "gas-station",
        "title": "Gas Station",
        "prompt": "Given gas and cost arrays, find the index of the station to start at to complete a full circuit, or -1 if impossible.",
        "pattern": "Greedy",
        "choices": ["Greedy", "Two Pointers", "Dynamic Programming", "Sliding Window"],
        "explanation": "If total gas >= total cost, a solution exists. Sweep once tracking running tank; reset start when it goes negative.",
        "clues": [
            "Existence + position",
            "Reset on deficit",
            "Single pass",
        ],
        "complexity": "O(n)",
    },
    {
        "id": "hand-of-straights",
        "title": "Hand of Straights",
        "prompt": "Given a hand of cards and group size, determine if you can rearrange them into groups of consecutive cards.",
        "pattern": "Greedy",
        "choices": ["Greedy", "Heap", "Hash Map", "Sorting"],
        "explanation": "Use a min-heap or sorted counts; repeatedly start a group at the smallest available value and consume the next groupSize-1 consecutive values.",
        "clues": [
            "Start from smallest forced",
            "Counts of cards",
            "Greedy grouping",
        ],
        "complexity": "O(n log n)",
    },
    {
        "id": "partition-labels",
        "title": "Partition Labels",
        "prompt": "Partition a string into as many parts as possible so that each letter appears in at most one part.",
        "pattern": "Greedy",
        "choices": ["Greedy", "Two Pointers", "Hash Map", "Sliding Window"],
        "explanation": "Record each character's last index, then sweep extending the current partition's end; cut whenever you reach it.",
        "clues": [
            "Last-occurrence map",
            "Extend until safe",
            "Greedy cuts",
        ],
        "complexity": "O(n)",
    },
    {
        "id": "insert-interval",
        "title": "Insert Interval",
        "prompt": "Given a list of non-overlapping sorted intervals and a new interval, insert it and merge if necessary.",
        "pattern": "Intervals",
        "choices": ["Intervals", "Greedy", "Two Pointers", "Sorting"],
        "explanation": "Iterate through intervals: append those before, merge those overlapping, then append the rest.",
        "clues": [
            "Sorted input",
            "Merge while overlap",
            "Three regions",
        ],
        "complexity": "O(n)",
    },
    {
        "id": "merge-intervals",
        "title": "Merge Intervals",
        "prompt": "Given an array of intervals, merge all overlapping intervals.",
        "pattern": "Intervals",
        "choices": ["Intervals", "Sorting", "Greedy", "Two Pointers"],
        "explanation": "Sort by start, then walk merging when the current's end >= next's start.",
        "clues": [
            "Sort + sweep",
            "Overlap detection on adjacency",
            "Linear merge after sort",
        ],
        "complexity": "O(n log n)",
    },
    {
        "id": "non-overlapping-intervals",
        "title": "Non-overlapping Intervals",
        "prompt": "Given an array of intervals, find the minimum number of intervals to remove so the rest are non-overlapping.",
        "pattern": "Greedy",
        "choices": ["Greedy", "Intervals", "Dynamic Programming", "Sorting"],
        "explanation": "Sort by end. Always keep the interval with the earliest end; drop any that overlap it.",
        "clues": [
            "Maximize compatible set",
            "Sort by end time",
            "Activity selection",
        ],
        "complexity": "O(n log n)",
    },
    {
        "id": "meeting-rooms",
        "title": "Meeting Rooms",
        "prompt": "Given an array of meeting time intervals, determine if a person could attend all meetings.",
        "pattern": "Intervals",
        "choices": ["Intervals", "Sorting", "Greedy", "Heap"],
        "explanation": "Sort intervals by start; check that each starts after the previous ends.",
        "clues": [
            "Sort to compare neighbors",
            "Pairwise overlap check",
            "Linear sweep",
        ],
        "complexity": "O(n log n)",
    },
    {
        "id": "happy-number",
        "title": "Happy Number",
        "prompt": "Determine if repeatedly replacing a number by the sum of squares of its digits eventually reaches 1.",
        "pattern": "Hash Map",
        "choices": ["Hash Map", "Math", "Fast and Slow Pointers", "Recursion"],
        "explanation": "Track seen values to detect cycles, or use slow/fast pointers on the digit-square sequence.",
        "clues": [
            "Cycle detection on a sequence",
            "Stops or repeats",
            "Set-based or pointer-based",
        ],
        "complexity": "O(log n)",
    },
    {
        "id": "plus-one",
        "title": "Plus One",
        "prompt": "Given a non-empty array of decimal digits representing a non-negative integer, return its value plus one.",
        "pattern": "Math",
        "choices": ["Math", "Array", "Two Pointers", "Recursion"],
        "explanation": "Iterate from the end carrying the +1; if all digits become zero, prepend a 1.",
        "clues": [
            "Decimal carry simulation",
            "Right-to-left scan",
            "Edge case all-nines",
        ],
        "complexity": "O(n)",
    },
    {
        "id": "pow-x-n",
        "title": "Pow(x, n)",
        "prompt": "Implement pow(x, n) computing x raised to the integer power n.",
        "pattern": "Math",
        "choices": ["Math", "Recursion", "Bit Manipulation", "Dynamic Programming"],
        "explanation": "Fast exponentiation: if n is even, x^n = (x^(n/2))^2; if odd, multiply by x. Handle negative n by inverting.",
        "clues": [
            "Halve the exponent",
            "Logarithmic depth",
            "Negative exponent inversion",
        ],
        "complexity": "O(log n)",
    },
    {
        "id": "multiply-strings",
        "title": "Multiply Strings",
        "prompt": "Multiply two non-negative integers represented as strings without using built-in big-integer libraries.",
        "pattern": "Math",
        "choices": ["Math", "Array", "Dynamic Programming", "Recursion"],
        "explanation": "Schoolbook multiplication: each pair of digits contributes to two indices in the result; handle carries at the end.",
        "clues": [
            "Digit-by-digit multiplication",
            "Manual carry propagation",
            "Result length is m + n",
        ],
        "complexity": "O(m*n)",
    },
    {
        "id": "single-number",
        "title": "Single Number",
        "prompt": "Given a non-empty array where every element appears twice except for one, find that single one.",
        "pattern": "Bit Manipulation",
        "choices": ["Bit Manipulation", "Hash Map", "Math", "Sorting"],
        "explanation": "XOR all numbers; pairs cancel out, leaving the unique number.",
        "clues": [
            "Pairs cancel",
            "Constant extra space",
            "Linear pass",
        ],
        "complexity": "O(n)",
    },
    {
        "id": "number-of-1-bits",
        "title": "Number of 1 Bits",
        "prompt": "Return the number of '1' bits in the binary representation of an unsigned integer.",
        "pattern": "Bit Manipulation",
        "choices": ["Bit Manipulation", "Math", "Recursion", "Dynamic Programming"],
        "explanation": "Repeatedly flip the lowest set bit (n &= n - 1) and count, or shift and mask each bit.",
        "clues": [
            "Bit-twiddling trick",
            "Loop runs once per set bit",
            "n & (n-1) clears the lowest 1",
        ],
        "complexity": "O(1)",
    },
    {
        "id": "counting-bits",
        "title": "Counting Bits",
        "prompt": "Given an integer n, return an array where ans[i] is the number of 1 bits in the binary representation of i for 0 <= i <= n.",
        "pattern": "Dynamic Programming",
        "choices": ["Dynamic Programming", "Bit Manipulation", "Math", "Recursion"],
        "explanation": "ans[i] = ans[i >> 1] + (i & 1); each index reuses the count from i shifted right.",
        "clues": [
            "Build on smaller answers",
            "Bit-shift recurrence",
            "Linear time",
        ],
        "complexity": "O(n)",
    },
    {
        "id": "reverse-bits",
        "title": "Reverse Bits",
        "prompt": "Reverse the bits of a 32-bit unsigned integer.",
        "pattern": "Bit Manipulation",
        "choices": ["Bit Manipulation", "Math", "Recursion", "Stack"],
        "explanation": "Iterate 32 times, shifting result left and OR-ing in the lowest bit of n; shift n right each iteration.",
        "clues": [
            "Bit-by-bit assembly",
            "Fixed 32 iterations",
            "Mask and shift",
        ],
        "complexity": "O(1)",
    },
    {
        "id": "missing-number",
        "title": "Missing Number",
        "prompt": "Given an array containing n distinct numbers in [0, n], find the one that is missing.",
        "pattern": "Bit Manipulation",
        "choices": ["Bit Manipulation", "Math", "Hash Map", "Sorting"],
        "explanation": "XOR indices with values; the missing number is the result. Or use n*(n+1)/2 minus the array sum.",
        "clues": [
            "Pairs cancel via XOR",
            "Math identity also works",
            "Constant extra space",
        ],
        "complexity": "O(n)",
    },
]
